version: "3.9"

services:
  ftp:
    restart: always
    container_name: ftpd-server
    image: stilliard/pure-ftpd:hardened
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      - "/volumes/ftp/user:/home/user/:rw"
      - "/volumes/ftp/pass:/etc/pure-ftpd/passwd"
      - "/volumes/ftp/pub:/home/ftp/pub" # Directory for anonymous access
    environment:
      # SSL Configuration
      VIRTUAL_HOST: hvantoan.io.vn
      LETSENCRYPT_HOST: hvantoan.io.vn
      # FTP Configuration
      PUBLICHOST: "hvantoan.io.vn"
      FTP_USER_NAME: "ftp"
      FTP_USER_PASS: "ftp"
      FTP_USER_HOME: "/home/user"
      # Allow anonymous access
      ANONYMOUS_ENABLE: "yes" # Enable anonymous access
      ANONYMOUS_UPLOAD: "no" # Allow anonymous uploads
      ANONYMOUS_READ: "yes" # Allow anonymous read access
    networks:
      - nginx-proxy

  postgres:
    container_name: postgres
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_DB: ventures
      POSTGRES_USER: ventures
      POSTGRES_PASSWORD: 123456789x@X
    ports:
      - 5432:5432
    volumes:
      - /volumes/postgres:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1024M
    networks:
      - nginx-proxy

  redis:
    image: redis:7.4
    container_name: redis_dc
    command: redis-server /usr/local/etc/redis/redis.conf
    environment:
      - VIRTUAL_HOST=redis.dc.hvantoan.io.vn
      - LETSENCRYPT_HOST=redis.dc.hvantoan.io.vn
    ports:
      - "6379:6379"
    volumes:
      - /volumes/redis:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true
