
services:
  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    environment:
      INITIAL_ADMIN_EMAIL: it.vantoan@gmail.com
      INITIAL_ADMIN_PASSWORD: 123456789x@X
      # Postgres parameters:
      DB_POSTGRES_HOST: "postgres"
      DB_POSTGRES_PORT: 5432
      DB_POSTGRES_USER: hota
      DB_POSTGRES_PASSWORD: 123456789x@X
      DB_POSTGRES_NAME: npm
      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
    volumes:
      - /volumes/data:/data
      - /volumes/letsencrypt:/etc/letsencrypt
    depends_on:
      - postgres
    networks:
      - nginx-proxy

  postgres:
    container_name: postgres
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_DB: hota
      POSTGRES_USER: hota
      POSTGRES_PASSWORD: 123456789x@X
    ports:
      - 5432:5432
    volumes:
      - /volumes/postgres:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1024M
    networks:
      - nginx-proxy

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: it.vantoan@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123456789x@X
    user: '$UID:$GID'
    ports:
      - "5050:80"
    volumes:
      - /volumes/pgadmin/lib:/var/lib/pgadmin
      - /volumes/pgadmin/log:/var/log/pgadmin
    networks:
      - nginx-proxy

  redis:
    image: redis:7.4
    container_name: redis_dc
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    volumes:
      - /volumes/redis:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true
