version: "3.9"

services:
  postgres:
    container_name: postgres
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_DB: hota
      POSTGRES_USER: hota
      POSTGRES_PASSWORD: 123456789x@X
    ports:
      - 5432:5432
    volumes:
      - /volumes/postgres:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1024M
    networks:
      - nginx-proxy

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: it.vantoan@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123456789x@X
      VIRTUAL_HOST: pgadmin.hvantoan.io.vn
      LETSENCRYPT_HOST: pgadmin.hvantoan.io.vn
    user: '$UID:$GID'
    ports:
      - "5050:5050"
    volumes:
      - /volumes/pgadmin:/var/lib/pgadmin
    networks:
      - nginx-proxy

  redis:
    image: redis:7.4
    container_name: redis_dc
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    environment:
      - VIRTUAL_HOST=redis.dc.hvantoan.io.vn
      - LETSENCRYPT_HOST=redis.dc.hvantoan.io.vn
    ports:
      - "6379:6379"
    volumes:
      - /volumes/redis:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true
