version: "3.9"

services:
  ftp:
    restart: always
    container_name: ftpd-server
    image: stilliard/pure-ftpd:hardened
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      - "/volumes/ftp/user:/home/user/:rw"
      - "/volumes/ftp/pass:/etc/pure-ftpd/passwd"
    environment:
      # SSL Configuration
      VIRTUAL_HOST: hvantoan.io.vn
      LETSENCRYPT_HOST: hvantoan.io.vn
      # FTP Configuration
      PUBLICHOST: "hvantoan.io.vn"
      FTP_USER_NAME: "ftp"
      FTP_USER_PASS: "ftp"
      FTP_USER_HOME: "/home/user"
    networks:
      - nginx-proxy

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/
      # SSL Configuration
      VIRTUAL_HOST: database.dc.hvantoan.io.vn
      LETSENCRYPT_HOST: database.dc.hvantoan.io.vn
    volumes:
      - postgres_data:/var/lib/postgresql/data/:rw
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1024M
    networks:
      - nginx-proxy

  redis:
    image: redis:7.4
    container_name: redis_dc
    command: redis-server /usr/local/etc/redis/redis.conf
    environment:
      - VIRTUAL_HOST=redis.dc.hvantoan.io.vn
      - LETSENCRYPT_HOST=redis.dc.hvantoan.io.vn
    ports:
      - "6379:6379"
    volumes:
      - /volumes/redis:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - nginx-proxy

volumes:
  postgres_data:

networks:
  nginx-proxy:
    external: true
