services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    env_file:
      - .env
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - SERVERURL=vpn.hvantoan.io.vn
      - SERVERPORT=51820
      - PEERS=4
      - PEERDNS=auto
      - INTERNAL_SUBNET=10.10.100.0
      # SSL Configuration
      - VIRTUAL_HOST=vpn.hvantoan.io.vn
      - LETSENCRYPT_HOST=vpn.hvantoan.io.vn

      - VIRTUAL_PORT=51820 # Cổng VPN
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      net.ipv4.conf.all.src_valid_mark: 1
    restart: unless-stopped
