version: "3.8"  # Sử dụng version 3.8 của Docker Compose

services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Ho_Chi_Minh  # Chỉnh sửa lại Asia/Ho_Chi_Minh cho đúng
      - SERVERURL=vpn.hvantoan.io.vn #optional
      - SERVERPORT=51820 #optional
      - PEERS=4 #optional
      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=10.10.100.0 #optional
      # SSL Configuration
      - VIRTUAL_HOST=vpn.hvantoan.io.vn
      - LETSENCRYPT_HOST=vpn.hvantoan.io.vn
      - VIRTUAL_PORT=51820                # Cổng VPN
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      net.ipv4.conf.all.src_valid_mark: 1
    restart: unless-stopped
