version: "3.9"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "/etc/nginx/certs"
    networks:
      - app_network

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    volumes_from:
      - "nginx-proxy"
    networks:
      - app_network

  ftp:
    restart: always
    container_name: ftpd-server
    image: stilliard/pure-ftpd:hardened
    ports:
      - 21:21
      - 20:20
      - 30000-30009:30000-30009
    volumes:
      - ./volumes/ftp/user:/home/user/:rw
      - './ftp/pass:/etc/pure-ftpd/passwd'
    environment:
      # SSL Configuration
      VIRTUAL_HOST: ftp.hvantoan.io.vn
      LETSENCRYPT_HOST: ftp.hvantoan.io.vn
      LETSENCRYPT_EMAIL: toan01473@gmail.com
      # FTP Configuration
      PUBLICHOST: "ftp.hvantoan.io.vn"
      FTP_USER_NAME: "ftp"
      FTP_USER_PASS: "ftp"
      FTP_USER_HOME: "/home/user"
      FTP_USER_UID: 33
      FTP_USER_GID: 33
      ADDED_FLAGS: "--tls=2"
      TLS_CN: "**** FTP"
      TLS_ORG: "*****"
      TLS_C: "VI"
      MAX_CONNECTIONS: "20"
    networks:
      - app_network

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ventures
      VIRTUAL_HOST: database.hvantoan.io.vn
      LETSENCRYPT_HOST: database.hvantoan.io.vn
      LETSENCRYPT_EMAIL: toan01473@gmail.com
    volumes:
      - ./volumes/postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'" ]
      interval: 5s
      timeout: 60s
      retries: 5
      start_period: 80s
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 512M
    networks:
      - app_network

  master:
    restart: always
    image: itvantoan/cb_ventures:master
    container_name: ventures_master
    pull_policy: always
    environment:
      VIRTUAL_HOST: ventures.hvantoan.io.vn
      LETSENCRYPT_HOST: ventures.hvantoan.io.vn
      LETSENCRYPT_EMAIL: toan01473@gmail.com
    ports:
      - "5000:3000"
    deploy:
      resources:
        limits:
          cpus: '0.7'
    networks:
      - app_network
  api:
    restart: always
    image: itvantoan/ventures_be:master
    container_name: ventures_api
    pull_policy: always
    environment:
      VIRTUAL_HOST: ventures.dc.hvantoan.io.vn
      LETSENCRYPT_HOST: ventures.dc.hvantoan.io.vn
      LETSENCRYPT_EMAIL: toan01473@gmail.com
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          cpus: '0.7'
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
