version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ventures
      - VIRTUAL_HOST=database.hvantoan.io.vn
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=5432
      - LETSENCRYPT_HOST=database.hvantoan.io.vn
      - LETSENCRYPT_EMAIL=toan01473@gmail.com
    volumes:
      - ./volumes/postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app_network
    restart: on-failure

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-it.vantoan@gmail.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-12345678x@X}
      - PGADMIN_CONFIG_SERVER_MODE=True
      - VIRTUAL_HOST=pgadmin.hvantoan.io.vn
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=5050
      - LETSENCRYPT_HOST=pgadmin.hvantoan.io.vn
      - LETSENCRYPT_EMAIL=toan01473@gmail.com
    ports:
      - "5050:80"
    volumes:
      - ./volumes/pgadmin:/var/lib/pgadmin
    networks:
      - app_network
    restart: on-failure

  nginx:
    restart: always
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/nginx/conf.d"
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "./volumes/proxy/certs:/etc/nginx/certs:ro"
    networks:
      - app_network

  nginx-gen:
    restart: always
    image: jwilder/docker-gen
    container_name: nginx-gen
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./volumes/proxy/templates/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro"
    volumes_from:
      - nginx
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    networks:
      - app_network

  letsencrypt-nginx-proxy-companion:
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./volumes/proxy/certs:/etc/nginx/certs:rw"
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
    networks:
      - app_network

  staging:
    restart: always
    image: itvantoan/cb_ventures:staging
    container_name: ventures_staging
    pull_policy: always
    environment:
      - VIRTUAL_HOST=ventures-staging.hvantoan.io.vn
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=5100
      - LETSENCRYPT_HOST=ventures-staging.hvantoan.io.vn
      - LETSENCRYPT_EMAIL=toan01473@gmail.com
    ports:
      - "5100:3000"
    networks:
      - app_network

  master:
    restart: always
    image: itvantoan/cb_ventures:master
    container_name: ventures_master
    pull_policy: always
    environment:
      - VIRTUAL_HOST=ventures.hvantoan.io.vn
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=5000
      - LETSENCRYPT_HOST=ventures.hvantoan.io.vn
      - LETSENCRYPT_EMAIL=toan01473@gmail.com
    ports:
      - "5000:3000"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge