version: "3.9"

services:
  master:
    restart: always
    image: itvantoan/cb_ventures:production
    container_name: cb_ventures
    pull_policy: always
    environment:
      API_URL: ${API_URL}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      # SSL Configuration
      VIRTUAL_HOST: ventures.hvantoan.io.vn
      LETSENCRYPT_HOST: ventures.hvantoan.io.vn
    ports:
      - "3000:3000"
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '0.7'
    networks:
      - nginx-proxy

  api:
    restart: always
    image: itvantoan/ventures_be:master
    container_name: ventures_be
    pull_policy: always
    environment:
      VIRTUAL_HOST: ventures.dc.hvantoan.io.vn
      LETSENCRYPT_HOST: ventures.dc.hvantoan.io.vn
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          cpus: '0.7'
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true
