version: "3.8"
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - letsencrypt-certs:/etc/nginx/certs
      - letsencrypt-html:/usr/share/nginx/html
      - /volumes/ftp/user/images:/usr/share/nginx/html/images:rw
      # Added configuration for vhost and conf directories
      - vhost:/etc/nginx/vhost.d
      - conf:/etc/nginx/conf.d
      - ./config:/etc/nginx/conf.d
    networks:
      - nginx-proxy

  letsencrypt-proxy:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - letsencrypt-certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - letsencrypt-html:/usr/share/nginx/html
    environment:
      - DEFAULT_EMAIL=toan01473@gmail.com
      - NGINX_PROXY_CONTAINER=nginx-proxy
    networks:
      - nginx-proxy
    depends_on:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true

volumes:
  letsencrypt-certs:
  letsencrypt-html:
  # Added named volumes for vhost and conf
  vhost:
  conf:
