version: '3'

services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ~/db/mysql:/var/lib/mysql
      - ./config.cnf:/etc/mysql/conf.d/config.cnf
      - ./init-dump:/docker-entrypoint-initdb.d
    environment:
      TERM: xterm
      APP_ENV: dev
      MYSQL_USER: vantoan
      MYSQL_PASSWORD: 123456789x@X
      MYSQL_DATABASE: chat
      MYSQL_ROOT_PASSWORD: 123456789x@X
    container_name: mysql
