version: "3.9"

services:
  jaeger:
    image: jaegertracing/all-in-one:1.45
    networks:
      - nginx-proxy
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
      - COLLECTOR_OTLP_ENABLED=true
      # SSL Configuration
      - VIRTUAL_HOST=jaeger.hvantoan.io.vn
      - LETSENCRYPT_HOST=jaeger.hvantoan.io.vn
      - VIRTUAL_PORT=16686
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14269:14269
      - 14250:14250
      - 9411:9411
      - 4317:4317
      - 4318:4318
networks:
  nginx-proxy:
    external: true
