version: "3.9"

services:
  master:
    restart: always
    image: itvantoan/cb_ventures:production
    container_name: cb_ventures
    pull_policy: always
    environment:
      API_URL: ${API_URL}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GITHUB_ID: ${GITHUB_ID}
      GITHUB_SECRET: ${GITHUB_SECRET}
      # SSL Configuration
      VIRTUAL_HOST: ventures.hvantoan.io.vn
      LETSENCRYPT_HOST: ventures.hvantoan.io.vn
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - nginx-proxy

  api:
    restart: always
    image: itvantoan/ventures_be:master
    container_name: ventures_be
    pull_policy: always
    environment:
      VIRTUAL_HOST: ventures.dc.hvantoan.io.vn
      LETSENCRYPT_HOST: ventures.dc.hvantoan.io.vn
    ports:
      - "8000:8000"
    volumes:
      - ./production/appsettings.json:/app/appsettings.json
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true
