name: CD Nginx Proxy

on:
  push:
    branches: [main]
    paths:
      - "nginx/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub
        uses: actions/checkout@v2

      - name: Rebuild NGINX
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            eval `ssh-agent -s`
            ssh-add ~/.ssh/github
            cd ~/ctx/host-config
            git pull
            cd nginx
            docker compose up --remove-orphans -d
